# Site settings
title: Richard B. Wagner
email: breckwagner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    An awesome site deticated to my musings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://breck.dev" # the base hostname & protocol for your site
twitter_username: breckwagner
github_username:  breckwagner

# Build settings
markdown: kramdown
